@startuml Workout
skinparam Style strictuml
skinparam genericDisplay old
skinparam classAttributeIconSize 0
skinparam monochrome true

!include BaseEntity.pu
!include Excercise.pu

class Workout{
    +name: String
    +description: String
    +creator: User
    +planWorkoutEntries: ICollection<WorkoutEntry>
    +groups: ICollection<TrainingGroup>
}

class FinishedWorkout{
    +workout: Workout
    +finishedWorkoutEntries: ICollection<FinishedWorkoutEntry>
}

abstract class WorkoutEntry<E extends Excercise>{
    +excercise: E
    +workout: Workout
}

abstract class FinishedWorkoutEntry<WE extends WorkoutEntry<? extends Excercise>>{
    +workoutEntry: WE
}

class WorkoutEntryCardio{
    +distance: double
    +duration: TimeSpan
}

class FinishedWorkoutEntryCardio{
    +distance: double
    +duration: TimeSpan
}

class WorkoutEntryStrength{
    +set: int
    +repetitions: int
    +weight: double
}

class FinishedWorkoutEntryStrength{
    +set: int
    +repetitions: int
    +weight: double
}

'associations
BaseEntity <|-- Workout
BaseEntity <|-- WorkoutEntry

WorkoutEntry <|-- WorkoutEntryCardio: <<bind>>E::ExcerciseCardio
WorkoutEntry <|-- WorkoutEntryStrength: <<bind>>E::ExcerciseStrength

WorkoutEntry "n" <--> "1" Workout

WorkoutEntryCardio "n" <--> "1" ExcerciseCardio 
WorkoutEntryStrength "n" <--> "1" ExcerciseStrength

BaseEntity <|-- FinishedWorkoutEntry
FinishedWorkoutEntry <|-- FinishedWorkoutEntryCardio: <<bind>>WE::WorkoutEntryCardio
FinishedWorkoutEntry <|-- FinishedWorkoutEntryStrength: <<bind>>WE::WorkoutEntryStrength

BaseEntity <|-- FinishedWorkout
'Assoziationen

hide empty members

@enduml