name: .NET

on:
  pull_request:
    branches: [ main ]

env:
  PROJECT_PATH: Source/Workoutisten.FitStreak/Workoutisten.FitStreak
  PROJECT_FILE: Workoutisten.FitStreak.csproj
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows10.0.19041
          - os: windows-latest
            platform: android
          - os: macos-latest
            platform: maccatalyst
          - os: macos-latest
            platform: ios

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Setup MSBuild
      if: ${{ matrix.platform == 'windows10.0.19041' }}
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-prerelease: true
        
    - uses: actions/setup-java@v2
      if: ${{ matrix.platform == 'android' }}
      with:
        distribution: 'microsoft'
        java-version: '11'
        
    - name: Install MAUI Workloads for Android, iOS or MacCatalyst
      if: ${{ (matrix.platform == 'android') || (matrix.platform == 'ios') || (matrix.platform == 'maccatalyst') }}
      run: dotnet workload install ${{ matrix.platform }} --ignore-failed-sources
        
    - name: Install .NET Maui
      run: dotnet workload install maui --ignore-failed-sources
      
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_FILE }}
      working-directory: ${{ env.PROJECT_PATH }}
      
    - name: Build Windows Application
      if: ${{ matrix.platform == 'windows10.0.19041' }}
      run: msbuild ${{ env.PROJECT_FILE }} -r -p:Configuration=Release -p:RestorePackages=false -p:TargetFramework=net6.0-windows10.0.19041
      working-directory: ${{ env.PROJECT_PATH }}
      
    - name: Build Android, iOS or MacCatalyst Application
      if: ${{ matrix.platform != 'windows10.0.19041' }}
      run: dotnet build ${{ env.PROJECT_FILE }} -c Release -f net6.0-${{ matrix.platform }} --no-restore
      working-directory: ${{ env.PROJECT_PATH }}
