name: Client Build

on:
  pull_request:
    branches: [ main ]

jobs:

# ***************************** #
# >>>>>>> Android build <<<<<<< #
# ***************************** #
  build-android:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Install .NET MAUI workloads
      shell: pwsh
      run: dotnet workload install maui --ignore-failed-sources

    - name: Generate version
      shell: pwsh
      id: version-creator
      run: |
        $buildDay = Get-Date -Format "yyyy.Mdd"
        $ver = $buildDay + "." + $GITHUB_RUN_NUMBER + ".0"
        echo "::set-output name=APP_VERSION::$ver"

    - name: Restore dependencies
      shell: pwsh
      run: dotnet restore Source/Workoutisten.FitStreak/Workoutisten.FitStreak/Workoutisten.FitStreak.csproj

    - name: Build project
      shell: pwsh
      run: dotnet build Source/Workoutisten.FitStreak/Workoutisten.FitStreak/Workoutisten.FitStreak.csproj -c Release -f net6.0-android --no-restore
    
    # - name: Upload build artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: android-v${{ steps.version-creator.outputs.APP_VERSION }}-artifacts
    #     path: '*Android\**\*-Signed.apk'


# ***************************** #
# >>>>>>> Windows Build <<<<<<< #
# ***************************** #
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-prerelease: true

    - name: Generate version
      shell: pwsh
      id: version-creator
      run: |
        $buildDay = Get-Date -Format "yyyy.Mdd"
        $ver = $buildDay + "." + $GITHUB_RUN_NUMBER + ".0"
        echo "::set-output name=APP_VERSION::$ver"

    - name: Install .NET MAUI workloads
      shell: pwsh
      run: dotnet workload install maui --ignore-failed-sources

    - name: Restore dependencies
      shell: pwsh
      run: dotnet restore Source/Workoutisten.FitStreak/Workoutisten.FitStreak/Workoutisten.FitStreak.csproj

    - name: Build project
      shell: pwsh
      run: msbuild Source/Workoutisten.FitStreak/Workoutisten.FitStreak/Workoutisten.FitStreak.csproj -r -p:Configuration=Release -p:TargetFramework=net6.0-windows10.0.19041
    
    # - name: Upload build artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: windows-v${{ steps.version-creator.outputs.APP_VERSION }}-artifacts
    #     path: '*Windows\**\*.msix'


# ************************* #
# >>>>>>> iOS Build <<<<<<< #
# ************************* #
  build-ios:
    runs-on: macos-12
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Generate version
      id: version-creator
      shell: bash
      run: |
        buildDay=`date +%Y.%m%d`
        echo $buildDay
        runNum=${{ env.GITHUB_RUN_NUMBER }}
        ver="${buildDay}.${runNum}.0"
        echo $ver
        echo "APP_VERSION=$ver" >> $GITHUB_ENV

    - name: Install .NET MAUI workloads
      shell: pwsh
      run: dotnet workload install maui --ignore-failed-sources

    - name: Restore dependencies
      shell: bash
      run: dotnet restore Source/Workoutisten.FitStreak/Workoutisten.FitStreak/Workoutisten.FitStreak.csproj
    
    - name: Build project
      shell: bash
      run: dotnet build Source/Workoutisten.FitStreak/Workoutisten.FitStreak/Workoutisten.FitStreak.csproj -c Release -f net6.0-ios --no-restore
    
    # - name: Upload iOS build artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: ios-v${{ steps.version-creator.outputs.APP_VERSION }}-artifacts
    #     path: '*iOS/**/*.app/**'


# ********************************* #
# >>>>>>> MacCatalyst Build <<<<<<< #
# ********************************* #
  build-macos:
    runs-on: macos-12
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Generate version
      id: version-creator
      shell: bash
      run: |
        buildDay=`date +%Y.%m%d`
        echo $buildDay
        runNum=${{ env.GITHUB_RUN_NUMBER }}
        ver="${buildDay}.${runNum}.0"
        echo $ver
        echo "APP_VERSION=$ver" >> $GITHUB_ENV

    - name: Install .NET MAUI workloads
      shell: pwsh
      run: dotnet workload install maui --ignore-failed-sources

    - name: Restore dependencies
      shell: bash
      run: dotnet restore Source/Workoutisten.FitStreak/Workoutisten.FitStreak/Workoutisten.FitStreak.csproj
    
    - name: Build project
      shell: bash
      run: dotnet build Source/Workoutisten.FitStreak/Workoutisten.FitStreak/Workoutisten.FitStreak.csproj -c Release -f net6.0-maccatalyst --no-restore
    
    # - name: Upload iOS build artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: maccatalyst-v${{ steps.version-creator.outputs.APP_VERSION }}-artifacts
    #     path: '*maccatalyst/**/*.app/**'
