name: .NET

on:
  pull_request:
    branches: [ main ]

env:
  PROJECT_PATH: Source/Workoutisten.FitStreak/Workoutisten.FitStreak
  PROJECT_FILE: Workoutisten.FitStreak.csproj
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2022
            platform: windows10.0.19041
            consoleType: pwsh
          - os: windows-2022
            platform: android
            consoleType: pwsh
          - os: macos-11
            platform: maccatalyst
            consoleType: bash
          - os: macos-11
            platform: ios
            consoleType: bash

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Setup MSBuild
      if: ${{ matrix.platform == 'windows10.0.19041' }}
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-prerelease: true
        
    - name: Install MAUI Workloads for Android, iOS or MacCatalyst
      if: ${{ (matrix.platform == 'ios') || (matrix.platform == 'maccatalyst') }}
      run: dotnet workload install ${{ matrix.platform }} --ignore-failed-sources
        
    - name: Install .NET Maui
      shell: pwsh
      run: dotnet workload install maui --ignore-failed-sources
      
    - name: Restore dependencies
      shell: ${{ matrix.consoleType }}
      run: dotnet restore ${{ env.PROJECT_FILE }}
      working-directory: ${{ env.PROJECT_PATH }}
      
    - name: Build Windows Application
      if: ${{ matrix.platform == 'windows10.0.19041' }}
      shell: ${{ matrix.consoleType }}
      run: |
        msbuild ${{ env.PROJECT_FILE }} -r -p:Configuration=Release -p:RestorePackages=false -p:TargetFramework=net6.0-windows10.0.19041
      working-directory: ${{ env.PROJECT_PATH }}
      
    - name: Build Android, iOS or MacCatalyst Application
      if: ${{ matrix.platform != 'windows10.0.19041' }}
      shell: ${{ matrix.consoleType}}
      run: dotnet build ${{ env.PROJECT_FILE }} -c Release -f net6.0-${{ matrix.platform }} --no-restore
      working-directory: ${{ env.PROJECT_PATH }}
