name: .NET

on:
  pull_request:
    branches: [ main ]

env:
  SOLUTION_PATH: Source/Workoutisten.FitStreak

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: Install .NET Maui
      run: dotnet workload install maui
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.SOLUTION_PATH}}
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{env.SOLUTION_PATH}}
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{env.SOLUTION_PATH}}
