name: Client Build

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'Source/Workoutisten.FitStreak/Workoutisten.FitStreak/**'
      - '.github/workflows/ClientBuild_OnPullRequest.yml' 

jobs:

# ***************************** #
# >>>>>>> Android build <<<<<<< #
# ***************************** #
  build-android:
    runs-on: windows-latest
    steps:
      - run: 'echo "No build required" '

# ***************************** #
# >>>>>>> Windows Build <<<<<<< #
# ***************************** #
  build-windows:
    runs-on: windows-latest
    steps:
      - run: 'echo "No build required" '


# ************************* #
# >>>>>>> iOS Build <<<<<<< #
# ************************* #
  build-ios:
    runs-on: macos-12
    steps:
      - run: 'echo "No build required" '


# ********************************* #
# >>>>>>> MacCatalyst Build <<<<<<< #
# ********************************* #
  build-macos:
    runs-on: macos-12
    steps:
      - run: 'echo "No build required" '
