name: .NET

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'Source/Workoutisten.FitStreak/Workoutisten.FitStreak/**'
      - '.github/workflows/ClientBuild_OnPullRequest.yml'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore Source/Workoutisten.FitStreak/Workoutisten.FitStreak.Server/Workoutisten.FitStreak.Server.csproj
      
    - name: Build
      run: dotnet build Source/Workoutisten.FitStreak/Workoutisten.FitStreak.Server/Workoutisten.FitStreak.Server.csproj -c Release --no-restore
